### ISSUE TITLE
下载项目里android源码后，在eclipse中打开项目，安装到手机上，点击app打不开闪退。

### ISSUE THREAD

**Issue by fangjj** [apicloudcom/photoBrowser#2]
04-02 23:58:49.182: I/WebViewFactory(15413): Loading com.google.android.webview version 51.0.2704.81 (code 270408100)
04-02 23:58:49.192: I/cr_LibraryLoader(15413): Time to load native libraries: 1 ms (timestamps 6187-6188)
04-02 23:58:49.192: I/cr_LibraryLoader(15413): Expected native library version number "51.0.2704.81", actual native library version number "51.0.2704.81"
04-02 23:58:49.232: E/APICloud(15413): Decompile Is A Stupid Behavior
04-02 23:58:49.232: D/AndroidRuntime(15413): Shutting down VM
04-02 23:58:49.242: E/app3c(15413): sorry, we have catch a crash log
04-02 23:58:49.242: E/app3c(15413): java.lang.RuntimeException: Unable to resume activity {com.apicloud.pkg.sdk/com.uzmap.pkg.EntranceActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.uzmap.pkg.uzapp.g.a(com.uzmap.pkg.uzcore.uzmodule.e)' on a null object reference
04-02 23:58:49.242: E/app3c(15413): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3007)
04-02 23:58:49.242: E/app3c(15413): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3038)
04-02 23:58:49.242: E/app3c(15413): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2409)
04-02 23:58:49.242: E/app3c(15413): 	at android.app.ActivityThread.access$800(ActivityThread.java:154)
04-02 23:58:49.242: E/app3c(15413): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315)
04-02 23:58:49.242: E/app3c(15413): 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-02 23:58:49.242: E/app3c(15413): 	at android.os.Looper.loop(Looper.java:135)
04-02 23:58:49.242: E/app3c(15413): 	at android.app.ActivityThread.main(ActivityThread.java:5290)
04-02 23:58:49.242: E/app3c(15413): 	at java.lang.reflect.Method.invoke(Native Method)
04-02 23:58:49.242: E/app3c(15413): 	at java.lang.reflect.Method.invoke(Method.java:372)
04-02 23:58:49.242: E/app3c(15413): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
04-02 23:58:49.242: E/app3c(15413): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
04-02 23:58:49.242: E/app3c(15413): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.uzmap.pkg.uzapp.g.a(com.uzmap.pkg.uzcore.uzmodule.e)' on a null object reference
04-02 23:58:49.242: E/app3c(15413): 	at com.uzmap.pkg.uzcore.UZAppActivity.onResume(UZAppActivity.java:351)
04-02 23:58:49.242: E/app3c(15413): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1257)
04-02 23:58:49.242: E/app3c(15413): 	at android.app.Activity.performResume(Activity.java:6125)
04-02 23:58:49.242: E/app3c(15413): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2996)
04-02 23:58:49.242: E/app3c(15413): 	... 11 more
04-02 23:58:49.242: E/AndroidRuntime(15413): FATAL EXCEPTION: main
04-02 23:58:49.242: E/AndroidRuntime(15413): Process: com.apicloud.pkg.sdk, PID: 15413
04-02 23:58:49.242: E/AndroidRuntime(15413): java.lang.RuntimeException: Unable to resume activity {com.apicloud.pkg.sdk/com.uzmap.pkg.EntranceActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.uzmap.pkg.uzapp.g.a(com.uzmap.pkg.uzcore.uzmodule.e)' on a null object reference
04-02 23:58:49.242: E/AndroidRuntime(15413): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3007)
04-02 23:58:49.242: E/AndroidRuntime(15413): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3038)
04-02 23:58:49.242: E/AndroidRuntime(15413): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2409)
04-02 23:58:49.242: E/AndroidRuntime(15413): 	at android.app.ActivityThread.access$800(ActivityThread.java:154)
04-02 23:58:49.242: E/AndroidRuntime(15413): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315)
04-02 23:58:49.242: E/AndroidRuntime(15413): 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-02 23:58:49.242: E/AndroidRuntime(15413): 	at android.os.Looper.loop(Looper.java:135)
04-02 23:58:49.242: E/AndroidRuntime(15413): 	at android.app.ActivityThread.main(ActivityThread.java:5290)
04-02 23:58:49.242: E/AndroidRuntime(15413): 	at java.lang.reflect.Method.invoke(Native Method)
04-02 23:58:49.242: E/AndroidRuntime(15413): 	at java.lang.reflect.Method.invoke(Method.java:372)
04-02 23:58:49.242: E/AndroidRuntime(15413): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
04-02 23:58:49.242: E/AndroidRuntime(15413): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
04-02 23:58:49.242: E/AndroidRuntime(15413): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.uzmap.pkg.uzapp.g.a(com.uzmap.pkg.uzcore.uzmodule.e)' on a null object reference
04-02 23:58:49.242: E/AndroidRuntime(15413): 	at com.uzmap.pkg.uzcore.UZAppActivity.onResume(UZAppActivity.java:351)
04-02 23:58:49.242: E/AndroidRuntime(15413): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1257)
04-02 23:58:49.242: E/AndroidRuntime(15413): 	at android.app.Activity.performResume(Activity.java:6125)
04-02 23:58:49.242: E/AndroidRuntime(15413): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2996)
04-02 23:58:49.242: E/AndroidRuntime(15413): 	... 11 more
04-02 23:58:49.252: I/Process(15413): Sending signal. PID: 15413 SIG: 9

**Comment by fangjj** [comment]
我想拓展这个模块，新增手势向上，向下两个事件。
{
     eventType: 'show',    //字符串类型；交互事件类型，取值范围如下：
                           //show：          打开浏览器并显示
                           //change：        用户切换图片
                           //click：         用户单击图片浏览器
                           //loadImgSuccess：网络图片下载成功的回调事件
                           //loadImgFail：   网络图片下载失败的回调事件
                           //longPress：     用户长按图片事件
                           **// up: 用户向上滑动
                           //down:用户向下滑动**
     index: 2              //数字类型；      当前图片在图片路径数组中的索引
}
请问如何实现，监听向上和向下事件。期待回复。

**Comment by fangjj** [comment]
我更换了最新的android-support-v4.jar就好了
